name: xxx
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.0
  - setuptools=69.5.1
  - cudatoolkit=12.1  # Explicitly specify CUDA toolkit (if GPU required)
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pandas=2.2.2
  - numpy=1.24.3
  - matplotlib=3.8.4
  - opencv=4.9.0.80
  - scikit-learn=1.4.2
  - jupyter  # Optional: Add if needed
  - pip:
      # Core Libraries
      - grad-cam==1.5.4
      - timm==1.0.9
      - wandb==0.19.0
      - yacs==0.1.8
      - fvcore==0.1.5.post20221221
      - huggingface-hub==0.24.6

      # Additional Dependencies
      - tqdm==4.66.5
      - scipy==1.9.2
      - tensorboard==2.18.0
      - protobuf==5.29.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - pillow==10.3.0